// <auto-generated />
namespace DinarakProject01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class initialization_1force : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialization_1force));
        
        string IMigrationMetadata.Id
        {
            get { return "202405241508082_initialization_1-force"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
